nova:
  chain_id: "nova"
  val_addr: "novavaloper18hcuafd3849v4deyyazn6k32ze9msyqs2xgvjh"
  bot_addr: "nova1lds58drg8lvnaprcue2sqgfvjnz5ljlkq9lsyf"
  client_addr: "nova1ma2378jplsnj3chlcgwqfx8p8g92z7dzxdvxmd"
gaia:
  chain_id: "gaia"
  denom: "uatom"
  decimal: 6
  val_addr: "cosmosvaloper1ma2378jplsnj3chlcgwqfx8p8g92z7dzw5kg5n"
  host_addr: "cosmos1mn52fx79ckzam60qa4ctgt5meyrk09xc6y6j8adqz3wynww7mczqhj6wur"
  client_addr: "cosmos1ma2378jplsnj3chlcgwqfx8p8g92z7dztqzacq"
net:
  ip:
    nova: "3.38.200.6"
    gaia: "3.36.104.92"
  port:
    grpc: 9090
    rest: 1317
    tmrpc: 26657
    p2p: 26656
    prometheus: 26660
