name: Build (XC)

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  USER_NAME: vvictorl

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        os: [darwin, linux]
        include:
          - os: darwin
            arch: arm64
    name: ${{ matrix.arch }} for ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          GOPRIVATE: github.com/Carina-labs

      - name: Build bot
        run: |
          git config --global url."https://${{ env.USER_NAME }}:${{ secrets.HAL_ACT }}@github.com".insteadOf "https://github.com"
          go mod download
          make build
          
