name: golangci-lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read

env:
  USER_NAME: ${{ secrets.REPO_USER }}

jobs:
  golangci:
    runs-on: ubuntu-latest
    name: golangci-lint start
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
        env:
          GOOS: linux
          GOARCH: amd64
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.go
          FILES: |
            go.mod
            go.sum
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=5m ./...
        if: env.GIT_DIFF
