name: Lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.go
          FILES: |
            go.mod
            go.sum
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
        if: env.GIT_DIFF
